encoding: utf-8
name: Navodita Sharma
url: https://navoditas.github.io/
author:
  name: Navodita Sharma
  email: navoditasharma16@gmail.com
description: Graduate Student at MIT.
permalink: /posts/:title/
include: ['_pages']
